language: php
php:
  - '7.1'
  - '7.2'
  - hhvm
services:
  - mysql
  - postgresql
before_install:
  - mysql -e 'CREATE DATABASE phact;'
  - psql -c 'CREATE DATABASE phact;' -U postgres
  - echo 'date.timezone = "Europe/Moscow"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
install:
  - travis_retry composer install --prefer-source --no-interaction
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml